Quick fix branch for recents
liwoo/cell-connect pull request #5
Opened 2024-06-04 01:33 UTC by glenmiracle18

Quick updates and rearrangements will come from this branch ❇️

2024-06-04 20:09 UTC, liwoo requested changes
Please pay attention to the CI/CD errors. A lot of them are actually useful.

Also never close issues until their corresponding PRs have been merged. 

You can tag an issue(s) to a PR as explained [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)

2024-06-04 20:09 UTC, liwoo commented on app/components/blocks/sidebar.tsx
> +          <nav className="grid items-start px-2 text-sm font-medium lg:px-4 gap-3">
you need to extract these nav items into an object, so we don't keep copy-pasting the same code

2024-06-04 20:09 UTC, liwoo commented on app/components/blocks/sidebar.tsx
> +            <img src="./famcon-logo.png" className="size-10" />
check the comment below and fix it

2024-06-04 20:09 UTC, liwoo commented on app/components/blocks/some-table.tsx
> +      <TableHeader>
again, extract the table information into a separate object and simply loop through it in your code to avoid duplication

2024-06-04 20:09 UTC, liwoo commented on app/components/layouts/header.tsx
> +            >
same comment about extracting objects here

2024-06-04 20:09 UTC, liwoo commented on app/components/blocks/layout-header.tsx
> +  title?: String;
replace `String` with `string` here

2024-06-06 18:27 UTC, liwoo approved these changes

2024-06-06 18:28 UTC, liwoo commented
@glenmiracle18 this is approved, jsut fix the code quality issue highlighted in CI/CD

2024-06-06 19:05 UTC, glenmiracle18 commented
> @glenmiracle18 this is approved, jsut fix the code quality issue highlighted in CI/CD

on it

2024-06-10 10:55 UTC, glenmiracle18 commented
> Please pay attention to the CI/CD errors. A lot of them are actually useful.
> 
> Also never close issues until their corresponding PRs have been merged.
> 
> You can tag an issue(s) to a PR as explained [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)

Hello sir, 
I just tag the PR to the issues I'm resolving.
I'll be on the watch for CI/CD errors

2024-06-10 17:59 UTC, merged